filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: false
      templates:
        - condition.contains:
            docker.container.image: jpbjesus/rabbitmq:latest 
          config:
            - module: rabbitmq
              access:
                input:
                  type: container
                  enabled: true
                  paths:
                    - /var/lib/docker/containers/${data.docker.container.id}/${data.docker.container.id}-json.log
                  processors:
                    - add_docker_metadata:
                        host: "unix:///var/run/docker.sock"
                    - decode_json_fields:
                        fields: ["message"]
                        target: "json"
                        overwrite_keys: true
output.elasticsearch:
  hosts: ['10.5.0.6:9200']
  indices:
    - index: 'filebeat-%{[agent.version]}-%{+yyyy.MM.dd}'
logging.json: true
logging.metrics.enabled: false

# templates:
#   - condition:
#       contains:
#         docker.container.image: jpbjesus/rabbitmq:latest 
#         # docker.container.image: haproxy-rsyslog
#     config:
#       - type: container
#         paths:
#           - /var/lib/docker/containers/${data.docker.container.id}/${data.docker.container.id}-json.log
#         # exclude_lines: ["^\\s+[\\-`('.|_]"]  # drop asciiart lines