version: '3'

services: 
    stats:
        image: bitnami/rabbitmq
        environment:
            - RABBITMQ_USERNAME=user
            - RABBITMQ_PASSWORD=password
            - RABBITMQ_NODE_TYPE=stats
            - RABBITMQ_NODE_NAME=rabbit@stats
            - RABBITMQ_ERL_COOKIE=s3cr3tc00ki3
        ports:
            - '15672:15672'
        networks:
            - cluster-network
        volumes:
            - 'stats_data:/rabbitmq'

    rabbitmq1:
        image: bitnami/rabbitmq
        environment:
            - RABBITMQ_NODE_TYPE=queue-disc
            - RABBITMQ_NODE_NAME=rabbit@rabbitmq1
            - RABBITMQ_CLUSTER_NODE_NAME=rabbit@stats
            - RABBITMQ_ERL_COOKIE=s3cr3tc00ki3
        volumes:
            - 'rabbitmq1:/rabbitmq'
        depends_on: 
            - stats
        networks:
            - cluster-network

    rabbitmq2:
        image: bitnami/rabbitmq
        environment:
            - RABBITMQ_NODE_TYPE=queue-disc
            - RABBITMQ_NODE_NAME=rabbit@rabbitmq2
            - RABBITMQ_CLUSTER_NODE_NAME=rabbit@stats
            - RABBITMQ_ERL_COOKIE=s3cr3tc00ki3
        volumes:
            - 'rabbitmq2:/rabbitmq'
        depends_on: 
            - stats
            - rabbitmq1
        networks:
            - cluster-network
    
    rabbitmq3:
        image: bitnami/rabbitmq
        environment:
            - RABBITMQ_NODE_TYPE=queue-disc
            - RABBITMQ_NODE_NAME=rabbit@rabbitmq3
            - RABBITMQ_CLUSTER_NODE_NAME=rabbit@stats
            - RABBITMQ_ERL_COOKIE=s3cr3tc00ki3
        volumes:
            - 'rabbitmq3:/rabbitmq'
        depends_on: 
            - stats
            - rabbitmq1
            - rabbitmq2
        networks:
            - cluster-network

    haproxy:
        image: jpbjesus/haproxy-rabbitmq
        ports:
            - "5672:5672"
            - "1936:1936"
        networks:
            - cluster-network

networks:
    cluster-network:
        external:
            name: cluster-network

volumes:
    stats_data:
        driver: local
    rabbitmq1:
        driver: local
    rabbitmq2:
        driver: local
    rabbitmq3:
        driver: local
