## Performance tests ##
version: '3.8'

networks:
    cluster-network:
        external: true
        name: cluster-network

services:
    basic-get:
        image: &perf-test-image pivotalrabbitmq/perf-test:2.9.1-ubuntu
        networks:
            - cluster-network
        environment:
            URI: "amqp://user:password@haproxy:5672/%2f"
            QUEUE: basic-get
            ROUTING_KEY: basic-get
            VARIABLE_RATE: "1:1,0:30"
            POLLING: "true"
            POLLING_INTERVAL: 5000
            AUTOACK: "false"
            SERVERS_STARTUP_TIMEOUT: &startup_timeout 60
            METRICS_PROMETHEUS: "true"
        deploy:
            mode: replicated
            replicas: 0
    
    basic-get-auto:
        image: *perf-test-image
        networks:
            - cluster-network
        environment:
            URI: "amqp://user:password@haproxy:5672/%2f"
            QUEUE: basic-get
            ROUTING_KEY: basic-get
            PRODUCERS: 0
            POLLING: "true"
            POLLING_INTERVAL: 5000
            AUTOACK: "true"
            SERVERS_STARTUP_TIMEOUT: *startup_timeout
            METRICS_PROMETHEUS: "true"
        deploy:
            mode: replicated
            replicas: 0
    
    greedy-consumer:
        image: *perf-test-image
        networks:
            - cluster-network
        environment:
            URI: "amqp://user:password@haproxy:5672/%2f"
            QUEUE: greedy-consumer
            ROUTING_KEY: greedy-consumer
            VARIABLE_RATE: "100:20,0:20"
            CONSUMER_RATE: 50
            QOS: 2000
            AUTOACK: "false"
            SERVERS_STARTUP_TIMEOUT: *startup_timeout
            METRICS_PROMETHEUS: "true"
        deploy:
            mode: replicated
            replicas: 0
    
    publisher-confirms:
        image: *perf-test-image
        networks:
            - cluster-network
        environment:
            URI: "amqp://user:password@haproxy:5672/%2f"
            QUEUE: publisher-confirms
            ROUTING_KEY: publisher-confirms
            AUTOACK: "true"
            VARIABLE_RATE: "12:30,25:30,50:30,100:30"
            CONFIRM: 1
            CONFIRM_TIMEOUT: 1
            SERVERS_STARTUP_TIMEOUT: *startup_timeout
            METRICS_PROMETHEUS: "true"
        deploy:
            mode: replicated
            replicas: 0
    
    slow-consumer-persistent:
        image: *perf-test-image
        networks:
            - cluster-network
        environment:
            URI: "amqp://user:password@haproxy:5672/%2f"
            QUEUE: ha3-slow-consumer-persistent
            ROUTING_KEY: slow-consumer-persistent
            QUEUE_ARGS: x-max-length=10000
            FLAG: persistent
            AUTO_DELETE: "false"
            SIZE: 51200
            VARIABLE_RATE: "100:20,0:20"
            CONSUMER_RATE: 50
            QOS: 50
            AUTOACK: "false"
            SERVERS_STARTUP_TIMEOUT: *startup_timeout
            METRICS_PROMETHEUS: "true"
        deploy:
            mode: replicated
            replicas: 0
        
    nack:
        image: *perf-test-image
        networks:
            - cluster-network
        environment:
            TIME: 60
            URI: "amqp://user:password@haproxy:5672/%2f"
            VARIABLE_RATE: "1:10,0:20"
            QUEUE: nack
            QUEUE_ARGS: x-max-length=100
            ROUTING_KEY: nack
            AUTOACK: "false"
            NACK: "true"
            QOS: 5
            CONSUMER_LATENCY: 3000000
            SERVERS_STARTUP_TIMEOUT: *startup_timeout
            METRICS_PROMETHEUS: "true"
        deploy:
            mode: replicated
            replicas: 0
        
    
    unroutable-return:
        image: *perf-test-image
        networks:
            - cluster-network
        environment:
            URI: "amqp://user:password@haproxy:5672/%2f"
            VARIABLE_RATE: "2:30,4:30,10:30"
            VARIABLE_SIZE: "100:30,200:30"
            CONSUMERS: 0
            FLAG: mandatory
            SERVERS_STARTUP_TIMEOUT: *startup_timeout
            METRICS_PROMETHEUS: "true"
        deploy:
            mode: replicated
            replicas: 0
        
    
    unroutable-drop:
        image: *perf-test-image
        networks:
            - cluster-network
        environment:
            URI: "amqp://user:password@haproxy:5672/%2f"
            VARIABLE_RATE: "5:30,10:30,20:30"
            VARIABLE_SIZE: "100:30,200:30"
            CONSUMERS: 0
            SERVERS_STARTUP_TIMEOUT: *startup_timeout
            METRICS_PROMETHEUS: "true"
        deploy:
            mode: replicated
            replicas: 0
        
    
    many-queues:
        image: *perf-test-image
        networks:
            - cluster-network
        environment:
            URI: "amqp://user:password@haproxy:5672/%2f"
            QUEUE_PATTERN: "mq%d"
            QUEUE_PATTERN_FROM: 1
            QUEUE_PATTERN_TO: 1000
            RATE: 1
            SERVERS_STARTUP_TIMEOUT: *startup_timeout
            METRICS_PROMETHEUS: "true"
        deploy:
            mode: replicated
            replicas: 0
        