# https://prometheus.io/docs/prometheus/latest/configuration/configuration/
global:
  # This is higher than RabbitMQ's collect_statistics_interval,
  # but still close enough to capture metrics that were refreshed within this interval
  # This value determines the range that we use with rate():
  # https://www.robustperception.io/what-range-should-i-use-with-rate
  scrape_interval: 15s # Default is every 1 minute.
  # scrape_timeout: 10s # Default is 10 seconds.
  evaluation_interval: 60s # Default is every 1 minute.

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # Alertmanager's default port is 9093
      - 'alertmanager:9093'

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"
  - "prometheus_alerting_rules.yml"

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'rabbitmq-server'
    static_configs:
      # - 'rabbitmq-node-0:15692'
      # - 'rabbitmq-node-1:15692'
      # - 'rabbitmq-node-2:15692'
      # - 'rabbitmq-node-3:15692'
      # - 'rabbitmq-node-4:15692'
      # - 'rabbitmq-node-5:15692'
      - targets: [ '10.2.0.1:15692' ]
        labels:
          instance: 'rabbitmq-node-0'
      - targets: [ '10.2.0.1:15693' ]
        labels:
          instance: 'rabbitmq-node-1'
      - targets: [ '10.2.0.1:15694' ]
        labels:
          instance: 'rabbitmq-node-2'
      - targets: [ '10.2.0.1:15695' ]
        labels:
          instance: 'rabbitmq-node-3'
      - targets: [ '10.2.0.1:15696' ]
        labels:
          instance: 'rabbitmq-node-4'
      - targets: [ '10.2.0.1:15697' ]
        labels:
          instance: 'rabbitmq-node-5'
  # - job_name: 'rabbitmq-perf-test'
  #   static_configs:
  #     - targets:
  #         - 'basic-get:8080'
  #         - 'basic-get-auto:8080'
  #         - 'greedy-consumer:8080'
  #         - 'publisher-confirms:8080'
  #         - 'slow-consumer-persistent:8080'
  #         # - 'nack:8080'
  #         - 'unroutable-return:8080'
  #         - 'unroutable-drop:8080'
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['10.2.0.1:18080']
      # - targets: ['cadvisor:8081']
  - job_name: 'node-exporter'
    static_configs:
      - targets: [ '10.2.0.1:9100' ]
        labels:
          instance: 'node-exporter-0'
      - targets: [ '10.2.0.1:9101' ]
        labels:
          instance: 'node-exporter-1'
      - targets: [ '10.2.0.1:9102' ]
        labels:
          instance: 'node-exporter-2'
      - targets: [ '10.2.0.1:9103' ]
      labels:
        instance: 'node-exporter-3'
      - targets: [ '10.2.0.1:9104' ]
      labels:
        instance: 'node-exporter-4'
      - targets: [ '10.2.0.1:9105' ]
        labels:
          instance: 'node-exporter-5'
      # - targets: ['node-exporter:9100']
