groups:
  - name: custom_rules 
    rules:
    - alert: RabbitMqClusterNodeDown
      expr: up{job="rabbitmq-server"} == 0
      for: 2m
      labels:
        severity: critical
      annotations:
        description: RabbitMQ "{{$labels.instance}}" is down
        summary: RabbitMQ Node "{{$labels.instance}}" Is Down
    
    - alert: RabbitMqClusterNotAllNodesRunning
      expr: sum(up{job="rabbitmq-server"}) by (job) < 6
      for: 5m
      labels:
        severity: critical
      annotations:
        description: Some RabbitMQ Cluster Nodes Are Down in Service "{{$labels.instance}}"
        summary: Some RabbitMQ Cluster Nodes Are Down in Service "{{$labels.instance}}"
    
    - alert: RabbitMqDiskSpaceAlarm
      expr: rabbitmq_resident_memory_limit_bytes{job="rabbitmq-server"} == 1
      for: 1m
      labels:
        severity: critical
      annotations:
        description: RabbitMQ Disk Space Alarm is going off. Which means the node hit highwater mark and has cut off network connectivity, see RabbitMQ WebUI
        summary: RabbitMQ "{{$labels.instance}}" is Out of Disk Space


    # - alert: RabbitMqMemoryAlarm
    #     expr: rabbitmq_node_mem_alarm{service="{{ template "rabbitmq-ha.fullname" . }}"} == 1
    #     for: 1m
    #     labels:
    #     severity: critical
    #     annotations:
    #     description: RabbitMQ High Memory Alarm is going off.  Which means the node hit highwater mark and has cut off network connectivity, see RabbitMQ WebUI
    #     summary: RabbitMQ is Out of Memory

    # - alert: RabbitMqMemoryUsageHigh
    #     expr: (rabbitmq_node_mem_used{service="{{ template "rabbitmq-ha.fullname" . }}"} / rabbitmq_node_mem_limit{service="{{ template "rabbitmq-ha.fullname" . }}"}) > .9
    #     for: 1m
    #     labels:
    #     severity: critical
    #     annotations:
    #     description: RabbitMQ Memory Usage > 90%
    #     summary: RabbitMQ Node > 90% Memory Usage

    # - alert: RabbitMqFileDescriptorsLow
    #     expr: (rabbitmq_fd_used{service="{{ template "rabbitmq-ha.fullname" . }}"} / rabbitmq_fd_total{service="{{ template "rabbitmq-ha.fullname" . }}"}) > .9
    #     for: 5m
    #     labels:
    #     severity: critical
    #     annotations:
    #     description: RabbitMQ File Descriptor Usage > 90%
    #     summary: RabbitMQ Low File Descriptor Available

    # - alert: RabbitMqDiskSpaceLow
    #     expr: predict_linear(rabbitmq_disk_space_available_bytes{up{job="rabbitmq-server"}}[15m], 1 * 60 * 60) < 1"}
    #     for: 5m
    #     labels:
    #     severity: critical
    #     annotations:
    #     description: RabbitMQ will hit disk limit in the next hr based on last 15 mins trend.
    #     summary: RabbitMQ is Low on Disk Space and will Run Out in the next hour